package login::Model::DB;
use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Conf::Schema::DB',
    overwrite_modifications => 1,
    
    connect_info => {
        dsn => 'dbi:mysql:temp_db:localhost:3306',
        user => 'root',
        password => 'root',
    }
);

=head1 NAME

login::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<login>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<login::Model::DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.54

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
